# Generated by Django 4.2.11 on 2024-05-17 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_on_get',
        ),
        migrations.RemoveField(
            model_name='order',
            name='requires_delivery',
        ),
    ]
