# Generated by Django 4.2.11 on 2024-05-17 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_delivery_address_remove_order_is_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
